### PR TITLE
[WIP] add cholesky_triangular.svg

### PR DESCRIPTION
**Pull request by ya-sh-vardh-an**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've formatted the new code by running `poetry run pre-commit run --all-files --show-diff-on-failure` before committing.
- [ ] I've added tests for new code.
- [ ] I've added docstrings for the new code.
- [x] I've added a file.

## Description

1. I've added cholesky_triangular.svg figure in `docs/_static/`.
2. I haven't added the file link to `docs/sharp_bits.md` file.
3. I've created a figure showing step-by-step cholesky factorisation with an example of 3x3 system.
4. I've also added operation counts and input-output for each step.

### self-thoughts

1. I am not sure with operation count validity for forward and backward substitution.
2. Should I add an appendix like box which shows what each symbol means (for eg, A = PSD matrix)?
3. I am looking forward to suggestions on improving the design to be more minimalistic or self-explanatory.
4. Should I also include a graph (execution time vs matrix size) comparing cholesky factorisation and dense covariance method?

 

Issue Number: #268

### CODE REVIEW

**Comment by thomaspinder** [comment]
Hi @ya-sh-vardh-an . This is a great first draft! I like the way you've sketched this out. I think, given the amount of math here, that decoupling the math from the sketch would be helpful. I think this will look cleaner and more consistent with our existing docs.

**Comment by ya-sh-vardh-an** [comment]
Hi, thank you for your feedback. Sorry, I might have doubts about the 'decoupling the math'. Please, correct me, is it like removing all the mathematical functions and make a cleaner look which is focused more on visual interpretation (like bijector_figure)?

**Comment by ya-sh-vardh-an** [comment]
Ok, understood. I will replace the mathematical symbol. Please let me know, if there are any more things that I should add or change.

**Comment by thomaspinder** [comment]
Closing due to inactivity. Please reopen if there are future developments.

**Comment by ya-sh-vardh-an** [comment]
Hi @thomaspinder , sorry for really late reply. I was busy with my courses. As you mention before, this time I tried to make it consistent with documentation and also apply some of creativity. Please let me know how it looks and what modifications I can do.
cholesky

**Pull request closed without merging**
